"""Criacao das tabelas iniciais

Revision ID: 0b5bbedbd982
Revises: 
Create Date: 2026-10-02 19:03:24.109512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5bbedbd982'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('negocio', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('instancia', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ultima_envio_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_token_hash'), 'tenants', ['token_hash'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('ultima_visita', sa.DateTime(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('opt_out', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('respondeu_em', sa.DateTime(), nullable=True),
    sa.Column('resposta_auto_enviada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_telefone'), 'clientes', ['telefone'], unique=False)
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.create_table('fila',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('agenda_id', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('campanha', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('erro', sa.String(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('simulado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fila_tenant_id'), 'fila', ['tenant_id'], unique=False)
    op.create_table('agenda',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('quando', sa.DateTime(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_quando'), 'agenda', ['quando'], unique=False)
    op.create_index(op.f('ix_agenda_tenant_id'), 'agenda', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenda_tenant_id'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_quando'), table_name='agenda')
    op.drop_table('agenda')
    op.drop_index(op.f('ix_fila_tenant_id'), table_name='fila')
    op.drop_table('fila')
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_telefone'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_tenants_token_hash'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
